# apiVersion: scheduling.k8s.io/v1
# kind: PriorityClass
# metadata:
#   name: low-priority-class
# value: 10
# globalDefault: false
# description: "This priority class should be used for low priority fah-cpu pods only."
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fah-cpu
  labels:
    app: fah-cpu
spec:
  selector:
    matchLabels:
      app: fah-cpu
  replicas: 2 # Set number of replicas to run - one replica per node
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: fah-cpu
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - fah-cpu
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: fah-cpu
          image: "qassociates/folding-on-cluster:latest"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 8000m # How much CPU you wish to donate per node
              memory: 256Mi
            requests:
              cpu: 400m
              memory: 256Mi
          volumeMounts: # Mount config.xml file
            - name: data
              mountPath: /etc/fahclient
      initContainers:
        - name: copy-ro-scripts
          image: busybox
          command:
            [
              "sh",
              "-c",
              "cp /etc/fahclient-config/config.xml /etc/fahclient/config.xml",
            ]
          volumeMounts:
            - name: fah-cpu-config
              mountPath: /etc/fahclient-config
            - name: data
              mountPath: /etc/fahclient
      volumes:
        - name: data
          emptyDir: {}
        - name: fah-cpu-config
          configMap:
            name: foldingathome-config
      # priorityClassName: low-priority-class
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foldingathome-config
data:
  config.xml: |
    <config>
      <!--
        To set your user name, team and passkey just edit the text
        in quotes below.
      -->
      <!-- Folding Slot Configuration -->
      <max-packet-size v='big'/>

      <!-- User Information -->
      <user value="Chris_Coates"/>         <!-- Enter your user name here -->
      <team value="265019"/>         <!-- Your team number -->
      <passkey value="de314fcaa4933380de314fcaa4933380"/>      <!-- 32 hexadecimal characters - Get your key at https://apps.foldingathome.org/getpasskey -->

      <power value="full"/>     <!-- Throttling this at K8s level -->
      <gpu value="false"/>      <!-- If true, attempt to autoconfigure GPUs -->
      <fold-anon value="false"/>

      <!-- Folding Slots
        No folding slot configuration is strictly necessary,  The client will
        automaticlaly choose a general good configuration for you.  However, here
        are some examples where you can do more customization:

          <slot id="0" type="CPU"/>

        or

          <slot id="0" type="CPU"/>
          <slot id="1" type="GPU"/>

        or
          <slot id='0' type='CPU'>
            <cpus v='12'/>
            <paused v='true'/>
          </slot>
          <slot id='1' type='GPU'>
            <pci-bus v='23'/>
            <pci-slot v='0'/>
          </slot>
          <slot id='2' type='GPU'>
            <pci-bus v='101'/>
            <pci-slot v='0'/>
          </slot>
        All slots in a configuration MUST have unique ids.
      -->
      <slot id='0' type='CPU'>
        <cpus v='4'/>
        <paused v='false'/>
      </slot>
      <slot id='1' type='CPU'>
        <cpus v='4'/>
        <paused v='false'/>
      </slot>
    </config>
---
